language: node_js

cache: bundler

before_install:
  rvm:
    - 2.2

install:
  - npm install -g bower
  - npm install -g grunt-cli

notifications:
  slack: sid-ai:YXPzg7RWB0PEW6ZUCUV6ZSX8

before_script:
  - bower install
  - npm install

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - npm run build
  - npm run test

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true # route your build to the container-based infrastructure for a faster build